import Card from 'react-bootstrap/Card';
import Button from 'react-bootstrap/Button';
import { useNavigate } from 'react-router-dom';

// the package info which not covered in our class 
// is from their website and some the comment is generated by 
// chatgpt for better understanding and memorizing

const ViewLogo = ({ pageName, description, address, buttonText }) => {
  // useNavigate is a hook from react-router-dom v6 that provides navigation functionality.
  // This allows us to programmatically change routes.
  const navigate = useNavigate();

  // handleNavigation is a function that is triggered on button click.
  // It uses the navigate function to change the current route to the specified address.
  const handleNavigation = () => {
    navigate(`/${address}`);
  };
    return (
      <Card style={{ width:'900px' , height: '90%'}} className='shadow-lg mx-auto p-3 my-3'>
        <Card.Body style={{display:'flex',flexDirection:'column',justifyContent:'space-between'}}>
          <div>
            <Card.Title className="fs-3 page-title" >{pageName}</Card.Title>
            <Card.Text>
            {description}
            </Card.Text>
          </div>
          <Button variant="outline-primary" onClick={handleNavigation}>{buttonText}</Button>
        </Card.Body>
      </Card>
  
    );
  }

export default ViewLogo;