import Card from 'react-bootstrap/Card';
import Button from 'react-bootstrap/Button';
import { useNavigate } from 'react-router-dom';

// the package info which not covered in our class 
// is from their website and some the comment is generated by 
// chatgpt for better understanding and memorizing

const ViewLogo = ({ pageName, description, address, buttonText, iconContent}) => {
  // useNavigate is a hook from react-router-dom v6 that provides navigation functionality.
  // This allows us to programmatically change routes.
  const navigate = useNavigate();

  // handleNavigation is a function that is triggered on button click.
  // It uses the navigate function to change the current route to the specified address.
  const handleNavigation = () => {
    navigate(`/${address}`);
  };
    return (
      // <div style={{ }} className=' mx-auto p-3 my-3'>
        <div style={{width:'350px' , height: '400px', borderRadius:'5%', backgroundColor:'white', display:'flex',flexDirection:'column',justifyContent:'space-between'}} className=' mx-auto p-3 my-3'>
            <div>
            <div style={{fontWeight:'bold', color:'#0d47a1',fontSize: 25, padding:'15px'}} >{pageName}</div>
            <p style={{color:'#2196f3'}}>___________________________________</p>
            <div>
            {description}
            </div>
            </div>
            {/* <i class="bi bi-book"></i> */}
            <div style={{display:'flex', flexDirection:'row', justifyContent:'center'}}>
            {iconContent}
            </div>
          <Button variant="outline-primary" onClick={handleNavigation}>{buttonText}</Button>
        </div>
      // </div>
  
    );
  }

export default ViewLogo;